version: '3.8'

services:
  matter-of-time:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ['/app/entrypoint.sh']
    command: ['node', '.output/server/index.mjs']

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d mydatabase']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
